In [ ]:
b=float(input('breadth of triangle\n'))
h=float(input('height of triangle\n'))
a=b*h/2
print('areaof triangle\n',a)

breadth of triangle
21.5
height of triangle
20
areaof triangle
 215.0


above is the area of triangle program

In [ ]:
x=15
y=20
t=x
x=y
y=t
print('swapped x \n',x)
print('swapped y \n',y)

swapped x 
 20
swapped y 
 15


to swap two variables

In [ ]:
ye=int(input('enter the year:\n'))
if(ye%4==0):
  print("leap year")
else:
  print("not leap year")


enter the year:
2000
leap year


to check leap year

In [ ]:
pn=int(input('enter number'))
primeind='yes'
for i in range (2,pn,1):
  if (pn%i == 0):
    primeind='no'
    break
if primeind=='yes':
  print('primenumber')
else:
  print('not a prime number')

enter number15
not a prime number


prime number

In [ ]:
num = 6
if num < 0:
    print ('Factorial does not exist')
elif num == 0:
    print(1)
else:
    fact = 1
    for i in range (1, num + 1):
        fact = fact * i
    print(fact)

720


factorial of 6

In [ ]:
no=int(input('enter number'))
for i in range(1,16):
  print(no,'x',i,'=',no*i)

enter number10
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100
10 x 11 = 110
10 x 12 = 120
10 x 13 = 130
10 x 14 = 140
10 x 15 = 150


nos btw 1 to n

In [ ]:
n=int(input("enter the n value: \n"))
for i in range(1,n+1):
  print(i,end='')

enter the n value: 
9
123456789

sum of n nos.

In [ ]:
ns=15
sn=ns*(ns+1)/2
print("sum of n numbers:  ",sn)

sum of n numbers:   120.0


palindrom of no.

In [ ]:
paln = int(input("enter the no.:  "))
temp = paln
reverse = 0
while temp > 0:
    remainder = temp % 10
    reverse = (reverse * 10) + remainder
    temp = temp // 10
if paln == reverse:
  print('Palindrome')
else:
  print("Not Palindrome")

enter the no.:  155
Not Palindrome


or we can also do like this

In [ ]:
palno = int(input("enter the no.:  "))
rev = int(str(palno)[::-1])
if palno == rev:
  print('Palindrome')
else:
  print("Not Palindrome")

enter the no.:  144
Not Palindrome


Generate randome no.

In [ ]:
import random
print(random.randint(0,88))

56


convert kilometers to miles

In [ ]:
km = int(input("enter the km:  "))
conv=0.62137
m=km*conv
print(km ,"kilometers is equalto ",m ,"miles")

enter the km:  2
2 kilometers is equalto  1.24274 miles


add two matrics

In [ ]:
import numpy as npy
A =[[10,2,3],
    [4,15,6],
    [7,8,39]]
B =[[29,8,7],
    [6,45,4],
    [3,2,51]]
res = npy.array(A) + npy.array(B)
print(res)

[[39 10 10]
 [10 60 10]
 [10 10 90]]


concatenate 2 strings

In [ ]:
h = "Hi"
j = "MaM"
k = h + j
print(k)

HiMaM


convert byte to string

In [ ]:
S1 = "Welcome"
print(type(S1))
S2 = b"Welcome"
print(type(S2))

<class 'str'>
<class 'bytes'>


round no.

In [ ]:
r=float(input("enter the no.:  "))
rou=round(r)
print(rou)

enter the no.:  17.444
17


prime no in interval

In [ ]:
s=int(input("start value: "))
e=int(input("end value: "))
for i in range(s,e+1):
  if i>1:
    for a in range(2,i):
      if  (i % a) == 0:
        break
    else:
      print(i)




start value: 2
end value: 60
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59


Fibonacci series

In [ ]:
fn=int(input("enter the range for series  "))
fn1,fn2=0,1
print(fn1,fn2,end='')
for i in range(2,fn):
  fn3=fn1+fn2
  fn1=fn2
  fn2=fn3
  print(fn3,end='')
print()


enter the range for series  10
0 112358132134


compound interest

In [ ]:
import math
p=float(input("Enter Principal Amount: "))
r=float(input("Enter Rate of Interest: "))
t=float(input("Enter Time Period in years: "))
amt = p * (math.pow((1 + (r/100)),t))
print("Compound Amount: ",amt)
CI = amt - p
print("Compound Interest", CI)

Enter Principal Amount: 20000
Enter Rate of Interest: 2.7
Enter Time Period in years: 2
Compound Amount:  21094.579999999994
Compound Interest 1094.5799999999945


Armstrong  no

In [ ]:
number = int(input("enter the no:  "))
temp = number
add_sum = 0
while temp != 0:
    k = temp % 10
    add_sum += k*k*k
    temp = temp//10
if add_sum == number:
    print('Given number is a three-digit Armstrong Number')
else:
    print('Given number is not an Armstrong Number')

enter the no:  233
Given number is not an Armstrong Number
